version: '3.9'

services: 
    django:
        build: .
        command: sh -c "gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi"
        volumes: 
            - ./API_server:/app
            - static_data:/app/static
        expose: 
            - 8000        
        environment:
            - DEBUG=1
        env_file:
            - .env

    db:
        image: postgres:13-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=user1
            - POSTGRES_PASSWORD=user1
            - POSTGRES_DB=netology_stocks_products

    nginx:
        image: nginx:1.19.8-alpine
        depends_on:
            - django
        ports:
            - "80:80"
        volumes: 
            - static_data:/var/www/html/static
            - ./nginx-conf.d:/etc/nginx/conf.d/default.conf

volumes:
    pg_data:
    static_data:
